# Repo: mayar-1995/azure-test
# File: azure-test.yml
resources:
  repositories:
    - repository: Azure-Templates
      type: github
      name: Azure-Templates

jobs:
- template: base-template.yml@Azure-Templates  # Template reference
