# Repo: mayar-1995/azure-test
# File: azure-test.yml
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
  
resources:
  repositories:
    - repository: mayar-1995/Azure-Templates
      type: github
      name: base-template.yml
      endpoint: mayar-1995

jobs:
- template: base-template.yml@Azure-Templates  # Template reference
